/* ATLAS · programme template, lift encyclopedia and defaults.
   Pure data: no DOM, no storage. Loaded first in the browser; also
   require()-able from Node for the test suite. */

/* ================= PROGRAMME ================= */
/* A block is a list of weeks. Each week sets the phase, the working sets for
   compounds and accessories, and the RIR target. The live plan is db.plan and
   every archived block keeps the plan it was run under. */
const PHASES=["Re-groove","Build","Peak","Deload"];
const W=(phase,comp,acc,rir)=>({phase,comp,acc,rir});
const PLAN_PRESETS={
  "6-week":[W("Re-groove",3,2,"3–4"),W("Re-groove",3,3,"3"),W("Build",4,3,"2"),W("Build",4,3,"2"),W("Peak",4,3,"1"),W("Deload",2,2,"4–5")],
  "4-week":[W("Build",3,3,"2"),W("Build",4,3,"2"),W("Peak",4,3,"1"),W("Deload",2,2,"4–5")],
  "5-week · no deload":[W("Re-groove",3,3,"3"),W("Build",4,3,"2"),W("Build",4,3,"2"),W("Peak",4,3,"1"),W("Peak",4,3,"1")],
  "8-week":[W("Re-groove",3,2,"3–4"),W("Re-groove",3,3,"3"),W("Build",4,3,"2"),W("Build",4,3,"2"),W("Build",4,4,"2"),W("Peak",4,3,"1"),W("Peak",5,3,"1"),W("Deload",2,2,"4–5")]
};
const DEFAULT_PLAN={name:"6-week",weeks:PLAN_PRESETS["6-week"]};
/* Open-ended plan: weeks count up from startDate forever. weeks[0] is a hard
   week, weeks[1] the light week that lands every `every` weeks (shifted by
   lightOffset when postponed). No block end, no rollover. */
const PHYSIQUE_PLAN={name:"ATLAS Physique",open:true,every:6,lightOffset:0,rampWeeks:2,startDate:null,
  weeks:[W("Build",3,3,"0–1"),W("Deload",2,2,"2–3")]};
/* User-adjustable defaults (Settings screen). Live values sit in db.settings. */
const DEFAULT_SETTINGS={
  bar:20,                                   /* kg, the bar the plate calculator loads */
  plates:[25,20,15,10,5,2.5,1.25],          /* kg per plate, what the gym actually has */
  rest:{comp:150,acc:90,super:30},          /* seconds: compounds, accessories, between paired lifts */
  theme:"dark"                              /* "dark" | "light" | "auto" (follow the system) */
};
const PLATE_OPTIONS=[25,20,15,10,5,2.5,1.25,1,0.5];
/* Barbell lifts get the plate calculator and the empty-bar warm-up step */
const isBarbellLift=name=>!!(EXDB[name]&&EXDB[name].eq==="Barbell");
const BIG_INC=new Set(["Back Squat","Romanian Deadlift","Leg Press","Hack Squat","Front Squat","Conventional Deadlift","Belt Squat"]);

const SUBS={
"Back Squat":["Hack Squat","Leg Press","Front Squat","Goblet Squat","Smith Machine Squat","Safety Bar Squat","Pendulum Squat"],
"Flat Dumbbell Bench Press":["Barbell Bench Press","Machine Chest Press","Smith Machine Bench","Push-Up","Chest Dip"],
"Chest-Supported Row":["Seated Cable Row","T-Bar Row","Machine Row","Single-Arm DB Row","Single-Arm Cable Row","Machine High Row"],
"Seated Leg Curl":["Lying Leg Curl","Nordic Curl (assisted)","Glute-Ham Raise"],
"Seated DB Shoulder Press":["Machine Shoulder Press","Smith Overhead Press","Standing Barbell Overhead Press","Arnold Press"],
"Cable Triceps Pushdown":["Rope Pushdown","Machine Dip","Bench Dip","Single-Arm Cable Pushdown","Machine Triceps Extension"],
"Incline DB Curl":["EZ-Bar Curl","Preacher Curl","Spider Curl","Barbell Curl"],
"Seated Calf Raise":["Standing Calf Raise","Leg-Press Calf Raise","Donkey Calf Raise","Single-Leg Calf Raise"],
"Cable Crunch":["Machine Crunch","Decline Sit-Up","Ab Wheel","Reverse Crunch","Weighted Sit-Up"],
"Romanian Deadlift":["Conventional Deadlift","45-Degree Back Extension","Good Morning","Dumbbell Romanian Deadlift","Stiff-Leg Deadlift","Trap Bar Deadlift"],
"Lat Pulldown":["Assisted Pull-Up","Pull-Up","Machine Pulldown","Chin-Up","Neutral-Grip Pulldown"],
"Incline Dumbbell Press":["Incline Machine Press","Incline Barbell Press","Low-to-High Cable Fly"],
"Leg Press":["Hack Squat","Back Squat","Belt Squat","Pendulum Squat","Smith Machine Squat"],
"Cable Lateral Raise":["DB Lateral Raise","Machine Lateral Raise","Lean-Away Lateral Raise"],
"Overhead Cable Triceps Extension":["Skull Crusher","Overhead DB Extension","Machine Triceps Extension"],
"Hammer Curl":["Cable Hammer Curl","Reverse Curl","Zottman Curl"],
"Hanging Knee Raise":["Captain's Chair Raise","Cable Crunch","Hanging Leg Raise","Reverse Crunch"],
"Hack Squat":["Bulgarian Split Squat","Leg Press","Back Squat","Pendulum Squat","Walking Lunge","Reverse Lunge"],
"Seated Cable Row":["Chest-Supported Row","Machine Row","T-Bar Row","Single-Arm Cable Row","Pendlay Row"],
"Machine Chest Press":["Flat Dumbbell Bench Press","Smith Machine Bench","Push-Up","Decline Bench Press"],
"45-Degree Back Extension":["Romanian Deadlift","Reverse Hyper","Good Morning","Machine Back Extension","Cable Pull-Through","Barbell Hip Thrust"],
"DB Lateral Raise":["Cable Lateral Raise","Machine Lateral Raise","Lean-Away Lateral Raise"],
"Reverse Pec Deck":["Face Pull","Bent-Over Reverse Fly","Cable Rear Delt Fly"],
"Cable Curl":["EZ-Bar Curl","DB Curl","Bayesian Cable Curl","Machine Preacher Curl"],
"Standing Calf Raise":["Seated Calf Raise","Leg-Press Calf Raise","Smith Machine Calf Raise","Donkey Calf Raise"]};

/* Explicit swaps for the default programme's lifts. The swap sheet also
   offers every other lift with the same group and movement pattern, so
   this table is for curated favourites, not an exhaustive list. */
/* ================= LIFT ENCYCLOPEDIA ================= */
const MUSCLE_NAMES={quads:"Quads",glutes:"Glutes",hamstrings:"Hamstrings",adductors:"Adductors",calves:"Calves",
chest:"Chest",lats:"Lats",upper_back:"Upper Back",lower_back:"Lower Back",traps:"Traps",
delts_front:"Front Delts",delts_side:"Side Delts",delts_rear:"Rear Delts",
biceps:"Biceps",triceps:"Triceps",forearms:"Forearms",abs:"Abs",obliques:"Obliques",hip_flexors:"Hip Flexors"};
const MUSCLE_MAP={
traps:["m-fr-traps","m-bk-traps"],delts_front:["m-fr-delts"],delts_side:["m-fr-delts","m-bk-delts"],
delts_rear:["m-bk-delts"],chest:["m-fr-chest"],biceps:["m-fr-biceps"],triceps:["m-bk-triceps"],
forearms:["m-fr-forearms","m-bk-forearms"],lats:["m-bk-lats"],upper_back:["m-bk-upperback"],
lower_back:["m-bk-lowerback"],abs:["m-fr-abs"],obliques:["m-fr-obliques"],hip_flexors:["m-fr-hipflex"],
glutes:["m-bk-glutes"],quads:["m-fr-quads"],hamstrings:["m-bk-hams"],adductors:["m-fr-adductors"],calves:["m-bk-calves","m-fr-calves"]};
const GROUPS=["Quads","Hams & Glutes","Chest","Back","Shoulders","Biceps","Triceps","Calves","Core"];

/* g: group · pat: movement pattern · eq: equipment · pri/sec: muscles · about: what & why · form: cues
   uni: 1 when the lift is trained one side at a time (kg and reps are logged per side)
   timed: 1 when a set is measured in seconds rather than reps (holds and carries) */
const EXDB={
/* ---- Quads ---- */
"Back Squat":{g:"Quads",pat:"Squat",eq:"Barbell",pri:["quads","glutes"],sec:["adductors","lower_back","abs"],
 about:"The benchmark lower-body lift — a deep knee bend with the bar on your back that loads the quads and glutes through the longest useful range of motion.",
 form:["Bar on rear delts, whole foot planted, brace before you descend","Sit down between your knees, not back onto a chair","Depth to just below parallel; drive the floor away","Big breath and re-brace at the top of every rep"]},
"Front Squat":{g:"Quads",pat:"Squat",eq:"Barbell",pri:["quads"],sec:["glutes","abs","upper_back"],
 about:"Racking the bar on the front delts keeps the torso upright, shifting nearly all the work onto the quads and easing the lower back.",
 form:["Bar sits on the front delts, elbows driven high, relaxed fingertips under it","Stay tall — if the elbows drop, the bar rolls forward","Sit straight down between the knees, full depth, drive up through mid-foot"]},
"Goblet Squat":{g:"Quads",pat:"Squat",eq:"Dumbbell",pri:["quads"],sec:["glutes","abs"],
 about:"A dumbbell held at the chest acts as a counterweight, making deep, upright squatting feel natural. The best variant for grooving technique.",
 form:["Hold one end of a dumbbell in both hands against the chest","Elbows drop inside the knees at the bottom","Stand tall between reps, whole foot planted"]},
"Hack Squat":{g:"Quads",pat:"Squat",eq:"Machine",pri:["quads"],sec:["glutes","adductors"],
 about:"A machine squat that locks the torso against a pad so you can push the quads to failure without balance or back fatigue ending the set first.",
 form:["Whole foot on the platform","Deep, controlled descent","Drive through mid-foot, don't lock hard at the top"]},
"Leg Press":{g:"Quads",pat:"Squat",eq:"Machine",pri:["quads"],sec:["glutes","adductors"],
 about:"The heaviest safe quad exercise in the gym — the back is fully supported, so the legs are the only limit.",
 form:["Feet mid-platform, hip width","Deep as you can without the lower back rolling off the pad","Don't lock the knees hard at the top"]},
"Belt Squat":{g:"Quads",pat:"Squat",eq:"Machine",pri:["quads"],sec:["glutes","adductors"],
 about:"The load hangs from a belt at the hips, so the legs squat heavy while the spine carries nothing. Ideal when the lower back needs a rest.",
 form:["Stand tall — the load is on the hips only","Squat deep; no bar means no balance penalty","Drive through mid-foot, control the descent"]},
"Bulgarian Split Squat":{uni:1,g:"Quads",pat:"Squat",eq:"Dumbbell",pri:["quads","glutes"],sec:["adductors","abs"],
 about:"A rear-foot-elevated single-leg squat. Brutal, humbling, and one of the best leg builders there is — each side works alone so nothing hides.",
 form:["Rear foot laces-down on the bench","Torso slightly forward, drop straight down","Drive through the front heel"]},
"Smith Machine Squat":{g:"Quads",pat:"Squat",eq:"Smith",pri:["quads","glutes"],sec:["adductors","abs"],
 about:"A fixed bar path lets you set the feet forward and sit into the quads without balancing the load — a safe way to push close to failure.",
 form:["Feet slightly forward of the bar so the torso stays upright","Control the descent, full depth, drive through the whole foot","Rack by rotating the bar only once the rep is finished"]},
"Safety Bar Squat":{g:"Quads",pat:"Squat",eq:"Barbell",pri:["quads","glutes"],sec:["upper_back","abs","lower_back"],
 about:"The padded yoke and forward handles keep the torso tall and spare the shoulders, so it squats like a cross between a back and a front squat.",
 form:["Hands on the handles, elbows down, chest up","Fight the bar's pull forward by staying tall","Same depth and drive as a back squat"]},
"Pendulum Squat":{g:"Quads",pat:"Squat",eq:"Machine",pri:["quads"],sec:["glutes","adductors"],
 about:"An arcing machine path that keeps you upright and takes the quads through a deep, stable range with almost no back involvement.",
 form:["Heels down, knees tracking over the toes","Sink to full depth and pause briefly at the bottom","Push through the mid-foot, don't slam the lockout"]},
"Leg Extension":{g:"Quads",pat:"Isolation",eq:"Machine",pri:["quads"],sec:[],
 about:"Pure knee extension against a pad — the only lift here that truly isolates the quads, and the best place to chase a hard burn safely.",
 form:["Back flat on the pad, roller just above the ankles","Extend fully and squeeze at the top for a beat","Lower under control, don't let the stack drop"]},
"Walking Lunge":{uni:1,g:"Quads",pat:"Squat",eq:"Dumbbell",pri:["quads","glutes"],sec:["hamstrings","adductors","abs"],
 about:"Stepping through alternating lunges trains each leg on its own and adds a balance demand. Log reps per leg.",
 form:["Long step, front shin roughly vertical","Drop the back knee to just above the floor","Push through the front heel to step through, stay tall"]},
"Reverse Lunge":{uni:1,g:"Quads",pat:"Squat",eq:"Dumbbell",pri:["quads","glutes"],sec:["hamstrings","adductors"],
 about:"Stepping backwards keeps the front knee more stable than a forward lunge and loads the glutes a little harder. Log reps per leg.",
 form:["Step back far enough that the front shin stays near vertical","Lower straight down with the torso tall","Drive through the front foot to return"]},
"Step-Up":{uni:1,g:"Quads",pat:"Squat",eq:"Dumbbell",pri:["quads","glutes"],sec:["hamstrings","calves"],
 about:"Stepping onto a box with one leg is a low-skill single-leg lift that punishes cheating with the back foot. Log reps per leg.",
 form:["Box around knee height","Whole foot on the box, drive through it","Don't push off the trailing foot — let the working leg do it"]},
"Sissy Squat":{g:"Quads",pat:"Squat",eq:"Bodyweight",pri:["quads"],sec:["abs"],
 about:"Leaning back with the hips open puts the quads under maximal stretch. Brutal for a bodyweight movement; add load only once reps are easy.",
 form:["Hold something for balance, knees travel forward, hips stay open","Lower until the quads are fully stretched","Rise by pulling the knees back, not by bending at the hip"]},
/* ---- Hams & Glutes ---- */
"Romanian Deadlift":{g:"Hams & Glutes",pat:"Hinge",eq:"Barbell",pri:["hamstrings","glutes"],sec:["lower_back","forearms","traps"],
 about:"The definitive hip hinge. Lowering the bar with near-straight knees stretches the hamstrings under load — exactly the stimulus that makes them grow.",
 form:["Soft knees, push hips straight back","Bar stays against the legs the whole way","Stop where hamstring stretch peaks — don't chase the floor","Squeeze the glutes through to stand, re-set the flat back each rep"]},
"Conventional Deadlift":{g:"Hams & Glutes",pat:"Hinge",eq:"Barbell",pri:["hamstrings","glutes","lower_back"],sec:["quads","traps","forearms","lats"],
 about:"Picking heavy weight up off the floor — the biggest total-body pull there is, with hips, hamstrings and the whole back working at once.",
 form:["Bar over mid-foot, shins close, flat back set before you pull","Push the floor away and stand up — bar drags up the legs","Lock out by squeezing the glutes, not leaning back","Re-set every rep; no bouncing off the floor"]},
"Good Morning":{g:"Hams & Glutes",pat:"Hinge",eq:"Barbell",pri:["hamstrings","glutes"],sec:["lower_back"],
 about:"A barbell hinge with the bar on the back — the long lever makes light weight feel heavy through the entire posterior chain.",
 form:["Soft knees, push the hips straight back","Stop when the hamstrings pull tight — torso near parallel","Back flat and the bar light; this one punishes ego"]},
"Seated Leg Curl":{g:"Hams & Glutes",pat:"Isolation",eq:"Machine",pri:["hamstrings"],sec:["calves"],
 about:"Curling from a seated position works the hamstrings at long muscle length — research keeps finding that grows them faster than lying curls.",
 form:["Hips pinned into the seat, don't let them lift","Curl all the way, pause a beat at full flexion","Slow 2–3 second negative"]},
"Lying Leg Curl":{g:"Hams & Glutes",pat:"Isolation",eq:"Machine",pri:["hamstrings"],sec:["calves"],
 about:"The classic face-down hamstring curl. A slightly shorter muscle length than seated, but still an excellent knee-flexion builder.",
 form:["Hips pressed into the bench the whole set","Curl to full flexion, pause a beat","Take 2–3 seconds on the way down"]},
"Nordic Curl (assisted)":{g:"Hams & Glutes",pat:"Isolation",eq:"Bodyweight",pri:["hamstrings"],sec:["glutes","calves"],
 about:"Ankles anchored, you lower your torso forward using nothing but hamstring strength. Assistance from a band or your hands makes it scalable.",
 form:["Anchor the ankles, body rigid from knees to head","Lower as slowly as possible — the negative is the exercise","Push back up with hands or a band; earn the full rep over months"]},
"45-Degree Back Extension":{g:"Hams & Glutes",pat:"Hinge",eq:"Bodyweight",pri:["glutes","hamstrings"],sec:["lower_back"],
 about:"Hinging over the 45° pad hits the glutes and hamstrings hard while the lower back only stabilises — hold a plate to the chest to progress.",
 form:["Hinge at the hips, flat back","Squeeze glutes hard at the top","Slow down, don't hyperextend"]},
"Reverse Hyper":{g:"Hams & Glutes",pat:"Hinge",eq:"Machine",pri:["glutes","hamstrings"],sec:["lower_back"],
 about:"Torso pinned, legs swinging up behind you — loads the glutes and hams while gently decompressing the spine instead of squashing it.",
 form:["Grip the handles hard, torso glued to the pad","Swing the legs to just above parallel, squeeze the glutes","Control the pendulum — no violent kipping"]},
"Barbell Hip Thrust":{g:"Hams & Glutes",pat:"Hinge",eq:"Barbell",pri:["glutes"],sec:["hamstrings","adductors"],
 about:"Back on a bench, bar across the hips, drive to full extension — the most direct heavy glute lift there is.",
 form:["Bench edge just below the shoulder blades","Shins vertical at the top, chin tucked","Squeeze hard at lockout without overarching the lower back"]},
"Machine Hip Thrust":{g:"Hams & Glutes",pat:"Hinge",eq:"Machine",pri:["glutes"],sec:["hamstrings"],
 about:"The same movement on a dedicated machine, with the belt and pad doing the setup so every rep starts in the same place.",
 form:["Pad across the hips, feet flat and shoulder width","Drive to a full lockout and hold a beat","Lower until the hips are just off the bottom, then repeat"]},
"Sumo Deadlift":{g:"Hams & Glutes",pat:"Hinge",eq:"Barbell",pri:["glutes","adductors","quads"],sec:["hamstrings","lower_back","traps","forearms"],
 about:"A wide stance and upright torso shift the work from the back onto the hips and inner thighs. Often the more comfortable pull for long-legged lifters.",
 form:["Toes out, shins near vertical, hands inside the knees","Wedge the hips in and pull the slack out before the bar leaves the floor","Knees out the whole way up"]},
"Trap Bar Deadlift":{g:"Hams & Glutes",pat:"Hinge",eq:"Barbell",pri:["glutes","quads","hamstrings"],sec:["lower_back","traps","forearms"],
 about:"Standing inside the bar centres the load and lets the knees bend more, so it pulls like a squat-hinge hybrid that is kind to the lower back.",
 form:["Neutral grip on the handles, chest up","Push the floor away rather than pulling the bar","Lock out standing tall, no lean back"]},
"Stiff-Leg Deadlift":{g:"Hams & Glutes",pat:"Hinge",eq:"Barbell",pri:["hamstrings","glutes"],sec:["lower_back","forearms"],
 about:"Like a Romanian deadlift but starting from the floor with straighter knees, for a longer hamstring stretch.",
 form:["Soft knees only, hips high","Bar stays against the legs, back flat","Stop where the back wants to round and drive the hips through"]},
"Dumbbell Romanian Deadlift":{g:"Hams & Glutes",pat:"Hinge",eq:"Dumbbell",pri:["hamstrings","glutes"],sec:["lower_back","forearms"],
 about:"The RDL with dumbbells — the natural pick when the barbell is taken or the load is light enough not to need one.",
 form:["Dumbbells slide down the front of the thighs","Hips travel back, shins stay vertical","Stand up by driving the hips forward, not by yanking with the back"]},
"Single-Leg RDL":{uni:1,g:"Hams & Glutes",pat:"Hinge",eq:"Dumbbell",pri:["hamstrings","glutes"],sec:["lower_back","abs"],
 about:"One leg at a time exposes side-to-side differences and trains hip stability. Keep it light and controlled. Log reps per leg.",
 form:["Hinge from the hip, back leg reaching straight behind","Hips stay square to the floor","Touch the dumbbell towards the standing foot, then drive up"]},
"Cable Pull-Through":{g:"Hams & Glutes",pat:"Hinge",eq:"Cable",pri:["glutes","hamstrings"],sec:["lower_back"],
 about:"Facing away from a low cable and hinging into it teaches the hip drive of a deadlift with almost no spinal load.",
 form:["Rope between the legs, step out far enough for tension","Push the hips back until the hamstrings load","Snap the hips through and squeeze at the top"]},
"Glute Kickback":{uni:1,g:"Hams & Glutes",pat:"Isolation",eq:"Cable",pri:["glutes"],sec:["hamstrings"],
 about:"Cable at the ankle, kicking straight back — isolates the glutes through full hip extension. Log reps per leg.",
 form:["Slight lean forward, hold the frame","Kick back and slightly up, not out to the side","Squeeze at the top, control the return"]},
"Hip Abduction Machine":{g:"Hams & Glutes",pat:"Isolation",eq:"Machine",pri:["glutes"],sec:[],
 about:"Pushing the knees outward against pads trains the glute medius, the side of the hip that most lifts miss.",
 form:["Sit tall, pads on the outside of the knees","Open as far as you can and pause","Bring the pads back slowly without letting them slam"]},
"Hip Adduction Machine":{g:"Hams & Glutes",pat:"Isolation",eq:"Machine",pri:["adductors"],sec:[],
 about:"Squeezing the knees together against pads is the only direct inner-thigh work here — useful if squats feel weak out of the hole.",
 form:["Set the pads wide but comfortable","Squeeze together and hold a beat","Open slowly under control"]},
"Glute-Ham Raise":{g:"Hams & Glutes",pat:"Isolation",eq:"Machine",pri:["hamstrings","glutes"],sec:["calves","lower_back"],
 about:"Feet locked in, body lowering and rising from the knee — the hamstrings work at both ends at once, hard.",
 form:["Knees just behind the pad, hips stay straight","Lower under control until the body is horizontal or beyond","Pull back up with the hamstrings, pressing the toes into the plate to help"]},
"Machine Back Extension":{g:"Hams & Glutes",pat:"Hinge",eq:"Machine",pri:["lower_back","glutes"],sec:["hamstrings"],
 about:"Seated back extension against a pad — direct, adjustable lower-back work without needing a barbell.",
 form:["Pad across the shoulder blades, hips against the seat","Extend until the torso is straight, no further","Return slowly, keep the neck neutral"]},
/* ---- Chest ---- */
"Flat Dumbbell Bench Press":{g:"Chest",pat:"Horizontal Push",eq:"Dumbbell",pri:["chest"],sec:["delts_front","triceps"],
 about:"Dumbbells let each side move freely through a deeper range than a bar, making this the best all-round chest builder for most lifters.",
 form:["Shoulder blades pinned back and down on the bench","Lower to just outside the chest, slight elbow tuck","Press up and slightly in — don't clang the bells"]},
"Barbell Bench Press":{g:"Chest",pat:"Horizontal Push",eq:"Barbell",pri:["chest"],sec:["delts_front","triceps"],
 about:"The classic press and the heaviest chest movement — feet planted, shoulder blades pinned, bar touching the lower chest.",
 form:["Shoulder blades back and down, slight arch, feet planted","Bar to the lower chest, forearms vertical at the bottom","Press up and slightly back towards the face","Never go near failure without a spotter or safeties"]},
"Machine Chest Press":{g:"Chest",pat:"Horizontal Push",eq:"Machine",pri:["chest"],sec:["delts_front","triceps"],
 about:"A fixed pressing path with zero balance demand — perfect for taking the chest to true failure safely, especially late in a session.",
 form:["Adjust seat so handles sit at mid-chest","Full range — deep stretch, full press","Constant tension, no resting at lockout"]},
"Smith Machine Bench":{g:"Chest",pat:"Horizontal Push",eq:"Smith",pri:["chest"],sec:["delts_front","triceps"],
 about:"Barbell bench on rails. The fixed path removes stabiliser demand so the pecs do more of the work — and failing is safe with the hooks.",
 form:["Set the bench so the bar touches the lower chest","Shoulder blades pinned throughout","Twist-rack the bar the instant a rep stalls — that's the point of the Smith"]},
"Incline Dumbbell Press":{g:"Chest",pat:"Horizontal Push",eq:"Dumbbell",pri:["chest","delts_front"],sec:["triceps"],
 about:"Pressing on a ~30° incline shifts the work up into the upper-chest fibres — the region most lifters are missing.",
 form:["Bench 30°, shoulder blades set","Lower to upper-chest line","Press up and slightly back over the face"]},
"Incline Barbell Press":{g:"Chest",pat:"Horizontal Push",eq:"Barbell",pri:["chest","delts_front"],sec:["triceps"],
 about:"The barbell version of the incline press — heavier loading for the upper chest at the cost of a little range of motion.",
 form:["Bench at 30–45°, shoulder blades set","Lower to just below the collarbones","Press to lockout without flaring the elbows wide"]},
"Incline Machine Press":{g:"Chest",pat:"Horizontal Push",eq:"Machine",pri:["chest","delts_front"],sec:["triceps"],
 about:"Upper-chest pressing with the machine catching the weight — take every set close to failure without a spotter.",
 form:["Seat height so handles start at upper-chest level","Deep stretch at the bottom, full press without shrugging","Constant tension — don't rest at lockout"]},
"Pec Deck":{g:"Chest",pat:"Isolation",eq:"Machine",pri:["chest"],sec:["delts_front"],
 about:"Arms sweeping together on a machine — the chest is isolated and the path is fixed, so you can chase the squeeze without stabilising anything.",
 form:["Seat set so the handles sit at mid-chest","Slight bend in the elbows, drive through the forearms","Squeeze the pads together, pause, open slowly"]},
"Cable Fly":{g:"Chest",pat:"Isolation",eq:"Cable",pri:["chest"],sec:["delts_front"],
 about:"Bringing two cable handles together in an arc keeps tension on the chest right through to the squeeze at the end.",
 form:["Slight forward lean, soft elbows","Sweep the hands in a wide arc to meet in front of the chest","Control the return until you feel the stretch"]},
"Low-to-High Cable Fly":{g:"Chest",pat:"Isolation",eq:"Cable",pri:["chest"],sec:["delts_front"],
 about:"Cables set low and swept upwards bias the upper chest and the front delts.",
 form:["Handles at hip height, step forward","Sweep up and in until the hands meet at eye level","Lower slowly along the same path"]},
"Dumbbell Fly":{g:"Chest",pat:"Isolation",eq:"Dumbbell",pri:["chest"],sec:["delts_front"],
 about:"Lying on a bench and opening the arms wide gives a deep chest stretch. Keep the weight moderate; the bottom is where people get hurt.",
 form:["Slight elbow bend held throughout","Lower until the chest is stretched, not until the shoulders complain","Bring the arms back together as if hugging a barrel"]},
"Decline Bench Press":{g:"Chest",pat:"Horizontal Push",eq:"Barbell",pri:["chest"],sec:["triceps","delts_front"],
 about:"A downward angle shortens the range and lets you press more, biasing the lower chest.",
 form:["Feet locked, shoulder blades pinned","Bar touches the lower chest, elbows around 45 degrees","Press up and slightly back, lock out fully"]},
"Chest Dip":{g:"Chest",pat:"Horizontal Push",eq:"Bodyweight",pri:["chest"],sec:["triceps","delts_front"],
 about:"Leaning forward on the dip bars and going deep turns the dip into one of the best chest builders available. Add a belt when bodyweight gets easy.",
 form:["Lean forward, elbows flared slightly","Lower until the shoulders are level with the elbows","Press up without slamming the lockout"]},
"Push-Up":{g:"Chest",pat:"Horizontal Push",eq:"Bodyweight",pri:["chest"],sec:["triceps","delts_front","abs"],
 about:"The original horizontal press. Elevate the feet or add a plate on the back once sets go past 20.",
 form:["Hands just outside the shoulders, body a straight line","Chest to the floor, elbows tucked around 45 degrees","Press to full lockout and squeeze the chest"]},
/* ---- Back ---- */
"Chest-Supported Row":{g:"Back",pat:"Horizontal Pull",eq:"Machine",pri:["lats","upper_back"],sec:["delts_rear","biceps","forearms"],
 about:"Rowing with the chest on a pad removes all momentum and lower-back strain — the purest way to load the mid-back and lats.",
 form:["Chest glued to the pad the whole set","Pull elbows back and down, squeeze the shoulder blades","Control the negative — no dropping the stack"]},
"Seated Cable Row":{g:"Back",pat:"Horizontal Pull",eq:"Cable",pri:["lats","upper_back"],sec:["delts_rear","biceps","lower_back"],
 about:"The staple horizontal pull — constant cable tension, a big stretch forward, and a hard squeeze at the navel.",
 form:["Neutral grip, chest tall","Pull to the navel, elbows tight","Let the weight stretch you forward under control"]},
"T-Bar Row":{g:"Back",pat:"Horizontal Pull",eq:"Barbell",pri:["lats","upper_back"],sec:["delts_rear","biceps","lower_back"],
 about:"A bar wedged in a corner, loaded close to your centre of mass — heavy mid-back work with less lower-back stress than a bent-over row.",
 form:["Hinge to ~45°, chest up, back flat","Pull the handle into the sternum, elbows tight","Lower under control until the arms are long"]},
"Machine Row":{g:"Back",pat:"Horizontal Pull",eq:"Machine",pri:["lats","upper_back"],sec:["delts_rear","biceps"],
 about:"A fixed rowing path with chest support — set the seat right and it's all back, with no cheating available.",
 form:["Chest against the pad, feet planted","Drive the elbows back, squeeze the shoulder blades together","Slow negative, full stretch between reps"]},
"Single-Arm DB Row":{uni:1,g:"Back",pat:"Horizontal Pull",eq:"Dumbbell",pri:["lats","upper_back"],sec:["delts_rear","biceps","obliques"],
 about:"One hand braced on a bench, the other rowing a dumbbell — a huge range of motion, and each side of the back works alone.",
 form:["Flat back, hand and knee braced on the bench","Pull the bell to the hip, not the armpit","Full stretch at the bottom — let the shoulder blade slide forward"]},
"Barbell Row":{g:"Back",pat:"Horizontal Pull",eq:"Barbell",pri:["lats","upper_back"],sec:["lower_back","delts_rear","biceps","forearms"],
 about:"The heavy free-weight row. Hinged over with a bar, it builds the entire back — and demands a rock-solid lower-back position.",
 form:["Hinge to 30–45°, flat back, bar hanging under the shoulders","Pull to the lower ribs, elbows at ~45°","No heaving — if the torso swings, the weight is too heavy"]},
"Lat Pulldown":{g:"Back",pat:"Vertical Pull",eq:"Cable",pri:["lats"],sec:["biceps","upper_back","delts_rear"],
 about:"The scalable vertical pull — a full stretch at the top and elbows driven down and back build the lats that give a back its width.",
 form:["Lean back slightly, chest up","Pull the bar to the upper chest, elbows down and back","Full stretch at the top of every rep"]},
"Machine Pulldown":{g:"Back",pat:"Vertical Pull",eq:"Machine",pri:["lats"],sec:["biceps","upper_back"],
 about:"A pulldown with a fixed arc — less setup fiddle, the same lat-building stretch and squeeze.",
 form:["Thighs locked under the pads","Pull the elbows down and back, chest tall","Let the weight stretch you fully at the top"]},
"Pull-Up":{g:"Back",pat:"Vertical Pull",eq:"Bodyweight",pri:["lats"],sec:["biceps","upper_back","abs","forearms"],
 about:"The king of vertical pulls — dragging your whole bodyweight up builds lats, arms and grip at once.",
 form:["Dead hang start, shoulders packed down","Pull the chest to the bar, elbows to the ribs","Full hang between reps — half reps build half a back"]},
"Assisted Pull-Up":{g:"Back",pat:"Vertical Pull",eq:"Machine",pri:["lats"],sec:["biceps","upper_back"],
 about:"The pull-up with a counterweight platform — full-range vertical pulling scaled to any strength level. Reduce the assistance over time.",
 form:["Same as a pull-up: dead hang, chest to bar","Set assistance so you fail inside the target rep range","Control the way down — no dropping"]},
"Pendlay Row":{g:"Back",pat:"Horizontal Pull",eq:"Barbell",pri:["upper_back","lats"],sec:["biceps","lower_back","forearms"],
 about:"A strict barbell row from a dead stop on the floor every rep — no momentum, no cheating the lockout.",
 form:["Torso parallel to the floor, back flat","Pull explosively to the lower chest","Lower to the floor and reset before the next rep"]},
"Meadows Row":{uni:1,g:"Back",pat:"Horizontal Pull",eq:"Barbell",pri:["lats","upper_back"],sec:["biceps","forearms","delts_rear"],
 about:"A landmine bar rowed one arm at a time with an overhand grip — a big stretch on the lat and a strong contraction. Log reps per arm.",
 form:["Stand beside the bar, feet staggered, hand on the sleeve","Pull the elbow high and back, let the shoulder blade move","Lower slowly and let the lat stretch"]},
"Inverted Row":{g:"Back",pat:"Horizontal Pull",eq:"Bodyweight",pri:["upper_back","lats"],sec:["biceps","delts_rear","abs"],
 about:"Hanging under a bar and rowing your body to it. Lower the bar to make it harder, raise it to make it easier.",
 form:["Body straight as a plank, heels on the floor","Pull the chest to the bar and squeeze the shoulder blades","Lower slowly to straight arms"]},
"Straight-Arm Pulldown":{g:"Back",pat:"Isolation",eq:"Cable",pri:["lats"],sec:["triceps","delts_rear"],
 about:"Sweeping a cable down with straight arms isolates the lats without the biceps helping.",
 form:["Slight lean forward, arms almost straight","Pull the bar down to the thighs in an arc","Let the arms rise until the lats stretch"]},
"Chin-Up":{g:"Back",pat:"Vertical Pull",eq:"Bodyweight",pri:["lats","biceps"],sec:["upper_back","forearms","abs"],
 about:"Pull-ups with a palms-facing grip — more biceps, a touch easier for most people, still one of the best back builders.",
 form:["Full hang, shoulders packed","Pull the chin over the bar, elbows to the ribs","Lower to straight arms every rep"]},
"Wide-Grip Lat Pulldown":{g:"Back",pat:"Vertical Pull",eq:"Cable",pri:["lats"],sec:["upper_back","biceps","delts_rear"],
 about:"A wide overhand grip shortens the range but pulls the elbows out to the sides, which loads the outer lats and upper back — the width muscles.",
 form:["Grip just outside shoulder width, slight lean back","Drive the elbows down and out towards the hips","Let the bar rise to a full stretch, don't shrug up with it"]},
"Neutral-Grip Pulldown":{g:"Back",pat:"Vertical Pull",eq:"Cable",pri:["lats"],sec:["biceps","upper_back","forearms"],
 about:"A parallel-grip handle puts the shoulders in their strongest pulling position, so it is often the pulldown people can push hardest.",
 form:["Slight lean back, chest up","Pull the handle to the upper chest, elbows down and back","Control the stretch at the top"]},
"Single-Arm Cable Row":{uni:1,g:"Back",pat:"Horizontal Pull",eq:"Cable",pri:["lats","upper_back"],sec:["biceps","forearms"],
 about:"Seated row one arm at a time — lets the torso rotate slightly for a longer lat stretch and exposes a weaker side. Log reps per arm.",
 form:["Reach forward and let the shoulder blade slide out","Pull the elbow back past the ribs","Return slowly, keep the torso mostly still"]},
"Machine High Row":{g:"Back",pat:"Vertical Pull",eq:"Machine",pri:["lats","upper_back"],sec:["biceps","delts_rear"],
 about:"A chest-supported pull from above and in front — halfway between a row and a pulldown, and very hard to cheat.",
 form:["Chest on the pad, arms extended","Drive the elbows down and back","Let the weight pull the arms back to a full stretch"]},
"Rack Pull":{g:"Back",pat:"Hinge",eq:"Barbell",pri:["upper_back","traps","glutes"],sec:["hamstrings","lower_back","forearms"],
 about:"A deadlift from pins set around knee height — heavy back and grip work without the hard part off the floor.",
 form:["Pins just below the knee","Hips back, chest up, pull the slack out","Lock out tall and squeeze the shoulder blades"]},
"Dead Hang":{timed:1,g:"Back",pat:"Isolation",eq:"Bodyweight",pri:["forearms","lats"],sec:["upper_back"],
 about:"Hanging from the bar with straight arms. Grip, shoulders and lats all get a stretch and a test. Measured in seconds.",
 form:["Full grip, thumbs around the bar","Let the shoulders rise, then gently pull them down","Breathe; stop the set before the grip fails outright"]},
"Barbell Shrug":{g:"Back",pat:"Isolation",eq:"Barbell",pri:["traps"],sec:["forearms"],
 about:"Shoulders straight up towards the ears against a heavy bar. The one lift here that trains the traps directly.",
 form:["Stand tall, arms straight","Lift the shoulders straight up, don't roll them","Pause at the top, lower slowly"]},
"Dumbbell Shrug":{g:"Back",pat:"Isolation",eq:"Dumbbell",pri:["traps"],sec:["forearms"],
 about:"Shrugs with dumbbells at the sides — a more natural line for the shoulders than a bar held in front.",
 form:["Arms straight, dumbbells at the sides","Shoulders straight up, hold a beat","Lower under control to a full stretch"]},
/* ---- Shoulders ---- */
"Seated DB Shoulder Press":{g:"Shoulders",pat:"Vertical Push",eq:"Dumbbell",pri:["delts_front","delts_side"],sec:["triceps","traps"],
 about:"The bread-and-butter overhead press — dumbbells demand control and work the delts through a full range.",
 form:["Back against the pad, ribs down, don't arch","Lower to ear level, press to lockout","Keep forearms vertical throughout"]},
"Machine Shoulder Press":{g:"Shoulders",pat:"Vertical Push",eq:"Machine",pri:["delts_front","delts_side"],sec:["triceps"],
 about:"Overhead pressing on rails — no balancing act, so the delts can take every set to the edge safely.",
 form:["Seat height so handles start at ear level","Press without shrugging the shoulders up","Lower slow, full stretch, no bounce"]},
"Smith Overhead Press":{g:"Shoulders",pat:"Vertical Push",eq:"Smith",pri:["delts_front","delts_side"],sec:["triceps","traps"],
 about:"A fixed-path overhead press — the rails handle the balance, you handle the effort.",
 form:["Bar path just in front of the face","Ribs down, glutes tight — don't lean back into an incline press","Rack the moment a rep stalls"]},
"Cable Lateral Raise":{g:"Shoulders",pat:"Isolation",eq:"Cable",pri:["delts_side"],sec:["traps"],
 about:"Constant cable tension from the very bottom makes this the highest-value side-delt exercise — the muscle never gets to rest.",
 form:["Cable behind the body, slight lean away","Lead with the elbow, raise to shoulder height","Slow negative — the cable pulls you back"]},
"DB Lateral Raise":{g:"Shoulders",pat:"Isolation",eq:"Dumbbell",pri:["delts_side"],sec:["traps"],
 about:"The classic width-builder — light dumbbells raised strictly to shoulder height, for high reps, forever.",
 form:["Slight forward lean, soft elbows","Raise to shoulder height, pinky slightly up","Lighter than you think — no swinging"]},
"Machine Lateral Raise":{g:"Shoulders",pat:"Isolation",eq:"Machine",pri:["delts_side"],sec:["traps"],
 about:"Pads on the upper arms remove grip and swing entirely — pure side delts, easy to push to failure.",
 form:["Line the shoulder up with the machine's pivot","Lead with the elbows to shoulder height","Slow negative — resist the machine on the way down"]},
"Reverse Pec Deck":{g:"Shoulders",pat:"Isolation",eq:"Machine",pri:["delts_rear"],sec:["upper_back","traps"],
 about:"Sitting face-in on the pec deck turns it into the simplest, most effective rear-delt isolation in the gym.",
 form:["Arms just below shoulder height","Pull apart with the rear delts, not the arms","Pause a beat at full spread"]},
"Face Pull":{g:"Shoulders",pat:"Isolation",eq:"Cable",pri:["delts_rear"],sec:["upper_back","traps"],
 about:"Pulling a rope to the face with elbows high trains the rear delts and the small rotator muscles that keep pressing shoulders healthy.",
 form:["Rope at upper-chest height, thumbs towards you","Pull towards the eyes, elbows high and wide","Finish each rep with a 'double-biceps' squeeze"]},
"Bent-Over Reverse Fly":{g:"Shoulders",pat:"Isolation",eq:"Dumbbell",pri:["delts_rear"],sec:["upper_back"],
 about:"Hinged over with light dumbbells sweeping wide — a rear-delt burner that needs nothing but a bench and bells.",
 form:["Hinge until the torso is near parallel","Sweep the arms wide, soft elbows locked in place","Light weight, no swinging — the rear delts are small"]},
"Standing Barbell Overhead Press":{g:"Shoulders",pat:"Vertical Push",eq:"Barbell",pri:["delts_front","delts_side"],sec:["triceps","upper_back","abs"],
 about:"The strict standing press: bar from the collarbones to lockout with the whole body bracing. The benchmark shoulder lift.",
 form:["Grip just outside the shoulders, elbows under the bar","Brace hard, press up and slightly back as the head moves out of the way","Lock out over the mid-foot with the head through"]},
"Arnold Press":{g:"Shoulders",pat:"Vertical Push",eq:"Dumbbell",pri:["delts_front","delts_side"],sec:["triceps"],
 about:"Starting palms-in and rotating out through the press adds range at the bottom and works the delts through more of their arc.",
 form:["Start with the dumbbells in front of the face, palms towards you","Rotate and press in one smooth movement","Reverse the path on the way down"]},
"Landmine Press":{uni:1,g:"Shoulders",pat:"Vertical Push",eq:"Barbell",pri:["delts_front"],sec:["chest","triceps","abs"],
 about:"Pressing a barbell anchored in a landmine, one arm at a time. The arc is shoulder-friendly and the core has to work. Log reps per arm.",
 form:["Stagger the feet, bar at the shoulder","Press up and forward along the bar's arc","Lower to the shoulder under control"]},
"Cable Rear Delt Fly":{g:"Shoulders",pat:"Isolation",eq:"Cable",pri:["delts_rear"],sec:["upper_back"],
 about:"Crossed cables pulled out and back — constant tension on the rear delts, the muscle that makes shoulders look finished from the side.",
 form:["Cables at shoulder height, grab them crossed","Pull out and back with soft elbows","Stop when the arms are in line with the shoulders, return slowly"]},
"Upright Row":{g:"Shoulders",pat:"Isolation",eq:"Cable",pri:["delts_side","traps"],sec:["biceps","forearms"],
 about:"Pulling a bar or cable up the front of the body to chest height hits the side delts and traps together. Keep the grip wide-ish and stop at the chest.",
 form:["Grip a little wider than the shoulders","Lead with the elbows, bar close to the body","Stop at the lower chest, lower slowly"]},
"Front Raise":{g:"Shoulders",pat:"Isolation",eq:"Dumbbell",pri:["delts_front"],sec:["chest"],
 about:"Raising a dumbbell straight out in front to shoulder height. Front delts get plenty from pressing, so treat this as a finisher, not a staple.",
 form:["Slight bend in the elbow, thumbs up or palms down","Raise to shoulder height, no higher","Lower slowly, don't swing"]},
"Lean-Away Lateral Raise":{uni:1,g:"Shoulders",pat:"Isolation",eq:"Dumbbell",pri:["delts_side"],sec:[],
 about:"Holding a post and leaning away puts the side delt under tension from the very start, where a normal lateral raise is slack. Log reps per arm.",
 form:["Hold the frame, lean out until the arm hangs clear of the body","Raise to shoulder height with a soft elbow","Lower slowly and keep the lean the whole set"]},
/* ---- Biceps ---- */
"Incline DB Curl":{g:"Biceps",pat:"Isolation",eq:"Dumbbell",pri:["biceps"],sec:["forearms"],
 about:"Curling on an incline bench puts the long head of the biceps on stretch — and the loaded stretch is where growth lives.",
 form:["Set the bench ~60°, let arms hang fully","Curl without swinging the shoulders forward","Full stretch at the bottom every rep"]},
"EZ-Bar Curl":{g:"Biceps",pat:"Isolation",eq:"EZ-Bar",pri:["biceps"],sec:["forearms"],
 about:"The heavy-duty curl — the angled grips spare the wrists while both arms move the most total weight.",
 form:["Elbows pinned to the sides","Curl without leaning back","Lower for a slow two-count every rep"]},
"Preacher Curl":{g:"Biceps",pat:"Isolation",eq:"EZ-Bar",pri:["biceps"],sec:["forearms"],
 about:"The pad kills all momentum and loads the biceps hardest in the stretched bottom half — brutal and honest.",
 form:["Armpits snug over the pad","Lower almost to straight arms — that stretch is the point","No bouncing out of the bottom"]},
"DB Curl":{g:"Biceps",pat:"Isolation",eq:"Dumbbell",pri:["biceps"],sec:["forearms"],
 about:"The standard curl — supinating each dumbbell as it rises squeezes every fibre of the biceps.",
 form:["Start palms neutral, twist to palms-up as you curl","Elbows stay at the sides","Full straight-arm hang at the bottom"]},
"Cable Curl":{g:"Biceps",pat:"Isolation",eq:"Cable",pri:["biceps"],sec:["forearms"],
 about:"The cable keeps the biceps loaded even at the bottom, where dumbbells go slack — perfect for high-rep pump work.",
 form:["Elbows fixed at your sides","Constant tension top to bottom","Squeeze hard at the top"]},
"Hammer Curl":{g:"Biceps",pat:"Isolation",eq:"Dumbbell",pri:["biceps","forearms"],sec:[],
 about:"Neutral-grip curling shifts the work to the brachialis and forearms — thicker arms and a stronger grip.",
 form:["Neutral grip, elbows pinned","No swing — strict up, controlled down","Squeeze at the top"]},
"Cable Hammer Curl":{g:"Biceps",pat:"Isolation",eq:"Cable",pri:["biceps","forearms"],sec:[],
 about:"Hammer curls on a rope — constant tension for the brachialis and forearms from bottom to top.",
 form:["Rope ends held neutral, elbows pinned","Curl high, squeeze, lower slow","Step back from the stack so there's tension at the bottom"]},
"Reverse Curl":{g:"Biceps",pat:"Isolation",eq:"EZ-Bar",pri:["forearms"],sec:["biceps"],
 about:"Curling with palms down hammers the forearm extensors and brachialis — the finishing touch for complete arms.",
 form:["Overhand grip, thumbs over the bar","Wrists straight — don't let them flop back","Lighter than a normal curl; strict form"]},
"Barbell Curl":{g:"Biceps",pat:"Isolation",eq:"Barbell",pri:["biceps"],sec:["forearms"],
 about:"The straight-bar curl: heavy, simple, and the one to treat like a compound if you want bigger arms.",
 form:["Elbows pinned at the sides","Curl to the shoulders without swinging the torso","Lower under control to full extension"]},
"Spider Curl":{g:"Biceps",pat:"Isolation",eq:"Dumbbell",pri:["biceps"],sec:["forearms"],
 about:"Chest on an incline bench, arms hanging straight down — the biceps work hardest at the top, where they usually get a rest.",
 form:["Chest against the bench, arms hanging vertical","Curl and squeeze hard at the top","Lower until the arms are fully straight"]},
"Concentration Curl":{uni:1,g:"Biceps",pat:"Isolation",eq:"Dumbbell",pri:["biceps"],sec:["forearms"],
 about:"Seated, elbow braced against the inner thigh, curling one arm — nothing else can help. Log reps per arm.",
 form:["Elbow braced on the inside of the thigh","Curl to the shoulder and squeeze","Lower slowly to a full stretch"]},
"Bayesian Cable Curl":{uni:1,g:"Biceps",pat:"Isolation",eq:"Cable",pri:["biceps"],sec:["forearms"],
 about:"Facing away from a low cable with the arm behind the body, so the biceps curl from a fully stretched position. Log reps per arm.",
 form:["Step forward until the arm is stretched behind you","Curl without letting the elbow drift forward","Return to a full stretch every rep"]},
"Machine Preacher Curl":{g:"Biceps",pat:"Isolation",eq:"Machine",pri:["biceps"],sec:["forearms"],
 about:"The preacher curl on a machine — the same braced elbows, but a fixed path that is easy to load consistently.",
 form:["Armpits over the top of the pad","Curl until the biceps are fully shortened","Lower to a full stretch without unloading"]},
"Zottman Curl":{g:"Biceps",pat:"Isolation",eq:"Dumbbell",pri:["biceps","forearms"],sec:[],
 about:"Curl palms-up, rotate at the top, lower palms-down — biceps on the way up and forearms on the way down.",
 form:["Curl with the palms up","Rotate to palms down at the top","Lower slowly in the pronated grip"]},
/* ---- Triceps ---- */
"Cable Triceps Pushdown":{g:"Triceps",pat:"Isolation",eq:"Cable",pri:["triceps"],sec:[],
 about:"The staple triceps move — elbows pinned, cable pressed to lockout. Simple, repeatable, easy to progress.",
 form:["Elbows pinned to your sides","Full lockout at the bottom, squeeze","Only the forearms move"]},
"Rope Pushdown":{g:"Triceps",pat:"Isolation",eq:"Cable",pri:["triceps"],sec:[],
 about:"The rope lets the hands split apart at the bottom for a harder lockout squeeze than any straight bar.",
 form:["Elbows pinned, pull the rope ends apart at the bottom","Full lockout, one-second squeeze","Only the forearms move"]},
"Machine Dip":{g:"Triceps",pat:"Vertical Push",eq:"Machine",pri:["triceps"],sec:["chest","delts_front"],
 about:"Dipping on a machine loads the triceps heavy with the chest assisting — no shoulder strain, no bodyweight limit.",
 form:["Sit tall, shoulders down away from the ears","Elbows track back, not flared wide","Press to full lockout"]},
"Bench Dip":{g:"Triceps",pat:"Vertical Push",eq:"Bodyweight",pri:["triceps"],sec:["chest","delts_front"],
 about:"Hands on a bench behind you, heels on the floor — a do-anywhere triceps builder. Add plates on the lap to progress.",
 form:["Shoulders down, chest up — don't sink into the neck","Descend until the upper arms are parallel","Lock out fully and squeeze"]},
"Overhead Cable Triceps Extension":{g:"Triceps",pat:"Isolation",eq:"Cable",pri:["triceps"],sec:[],
 about:"Working overhead puts the long head — half the triceps' mass — on full stretch, which pushdowns never do.",
 form:["Face away, elbows by the ears","Full stretch behind the head","Extend to lockout without flaring"]},
"Overhead DB Extension":{g:"Triceps",pat:"Isolation",eq:"Dumbbell",pri:["triceps"],sec:[],
 about:"One dumbbell held in both hands, lowered behind the head — the classic long-head stretch with no cable needed.",
 form:["Seated, one bell in both hands overhead","Lower behind the head to a deep stretch","Elbows point forward, not out wide"]},
"Skull Crusher":{g:"Triceps",pat:"Isolation",eq:"EZ-Bar",pri:["triceps"],sec:[],
 about:"Lowering an EZ-bar to the forehead — or just behind it — loads the triceps deep in the stretch. The heavy-duty extension.",
 form:["Lower to the forehead or just behind the head","Elbows stay in — don't let them flare","Keep a rep in the tank; failing mid-rep here is grim"]},
"Close-Grip Bench Press":{g:"Triceps",pat:"Horizontal Push",eq:"Barbell",pri:["triceps","chest"],sec:["delts_front"],
 about:"A bench press with the hands at shoulder width, so the triceps take the brunt. The heaviest triceps work you can do.",
 form:["Hands about shoulder width, wrists stacked","Elbows tucked, bar to the lower chest","Press to lockout and finish the rep with the triceps"]},
"Weighted Dip":{g:"Triceps",pat:"Vertical Push",eq:"Bodyweight",pri:["triceps","chest"],sec:["delts_front"],
 about:"Upright dips with a belt or vest, elbows close — triceps first, chest second.",
 form:["Torso upright, elbows tucked back","Lower until the elbows are at 90 degrees","Press to a full lockout"]},
"Single-Arm Cable Pushdown":{uni:1,g:"Triceps",pat:"Isolation",eq:"Cable",pri:["triceps"],sec:[],
 about:"Pushdown one arm at a time — lets you turn the wrist out at the bottom for a harder contraction and evens out the arms. Log reps per arm.",
 form:["Elbow pinned, upper arm still","Extend fully and rotate the palm out slightly","Return until the forearm is above parallel"]},
"Triceps Kickback":{uni:1,g:"Triceps",pat:"Isolation",eq:"Dumbbell",pri:["triceps"],sec:[],
 about:"Bent over with the upper arm parallel to the floor, extending a dumbbell behind you. Light weight, hard squeeze. Log reps per arm.",
 form:["Upper arm parallel to the floor and still","Extend until the arm is straight and hold a beat","Lower without dropping the elbow"]},
"Machine Triceps Extension":{g:"Triceps",pat:"Isolation",eq:"Machine",pri:["triceps"],sec:[],
 about:"A seated machine extension — fixed path, easy to load, and no wrist strain late in the session.",
 form:["Elbows on the pad, upper arms still","Extend fully and pause","Return slowly, keep tension on the stack"]},
"Diamond Push-Up":{g:"Triceps",pat:"Horizontal Push",eq:"Bodyweight",pri:["triceps","chest"],sec:["delts_front","abs"],
 about:"Push-ups with the hands together under the chest so the triceps do most of the lifting.",
 form:["Thumbs and index fingers touching under the chest","Elbows track back, body straight","Lower to the hands, press to lockout"]},
/* ---- Calves ---- */
"Seated Calf Raise":{g:"Calves",pat:"Isolation",eq:"Machine",pri:["calves"],sec:[],
 about:"Bent-knee raises target the soleus — the deep calf muscle that does the daily work and responds to high reps.",
 form:["Full stretch at the bottom — pause there","Drive up onto the balls of the feet, pause at top","No bouncing out of the bottom"]},
"Standing Calf Raise":{g:"Calves",pat:"Isolation",eq:"Machine",pri:["calves"],sec:[],
 about:"Straight-knee raises hit the gastrocnemius — the diamond-shaped muscle that gives the calf its shape.",
 form:["Full stretch at the bottom, pause","Rise as high as possible, pause","Straight knees throughout"]},
"Leg-Press Calf Raise":{g:"Calves",pat:"Isolation",eq:"Machine",pri:["calves"],sec:[],
 about:"Calf raises on the leg-press platform — a huge stretch, heavy loading, and the easiest setup in the gym.",
 form:["Balls of the feet on the platform's bottom edge","Full stretch, pause, full rise, pause","Don't let the knees bounce"]},
"Donkey Calf Raise":{g:"Calves",pat:"Isolation",eq:"Machine",pri:["calves"],sec:[],
 about:"Bent at the hips with the load on the lower back, the calves work with the hamstrings stretched — many people feel it more than a standing raise.",
 form:["Hips bent, legs straight","Drop the heels to a full stretch","Rise onto the toes and hold at the top"]},
"Single-Leg Calf Raise":{uni:1,g:"Calves",pat:"Isolation",eq:"Dumbbell",pri:["calves"],sec:[],
 about:"One leg on a step with a dumbbell in the same hand. Finds the weaker calf fast. Log reps per leg.",
 form:["Ball of the foot on the step, hold something for balance","Full stretch at the bottom, pause","Rise all the way up, pause again"]},
"Smith Machine Calf Raise":{g:"Calves",pat:"Isolation",eq:"Smith",pri:["calves"],sec:[],
 about:"Standing raise under a Smith bar with the toes on a block — heavy load, stable path.",
 form:["Bar across the upper back, toes on a block","Lower until the calves are fully stretched","Rise high and squeeze for a beat"]},
"Hack Squat Calf Raise":{g:"Calves",pat:"Isolation",eq:"Machine",pri:["calves"],sec:[],
 about:"Toes on the edge of the hack squat plate, legs straight, calves doing the work. A neat substitute when there is no dedicated machine.",
 form:["Toes on the bottom edge of the platform","Keep the knees straight","Full stretch, full rise, no bouncing"]},
/* ---- Core ---- */
"Cable Crunch":{g:"Core",pat:"Core",eq:"Cable",pri:["abs"],sec:["obliques"],
 about:"Kneeling crunches against a cable stack — the abs are a muscle like any other, so load them and progress them like one.",
 form:["Hips stay still — flex the spine, don't pull with arms","Crunch ribs towards pelvis","Exhale hard at the bottom"]},
"Machine Crunch":{g:"Core",pat:"Core",eq:"Machine",pri:["abs"],sec:["obliques"],
 about:"A weighted crunch with a selectorised stack — the easiest way to progressively overload the abs.",
 form:["Ribs towards pelvis; the spine flexes, the hips stay put","Exhale hard as you crunch","Slow return, keep tension at the top"]},
"Decline Sit-Up":{g:"Core",pat:"Core",eq:"Bodyweight",pri:["abs"],sec:["hip_flexors","obliques"],
 about:"Sit-ups on a decline bench — gravity ramps the difficulty, and a plate held to the chest scales it forever.",
 form:["Curl the spine up one segment at a time","Down slow — the negative counts","Hold a plate on the chest to progress"]},
"Ab Wheel":{g:"Core",pat:"Core",eq:"Bodyweight",pri:["abs"],sec:["obliques","lats"],
 about:"Rolling out from the knees forces the abs to resist extension through a huge range — one of the hardest and best core moves.",
 form:["Start on the knees, hips slightly tucked","Roll only as far as the lower back stays flat","Pull back with the abs, not the arms"]},
"Hanging Knee Raise":{g:"Core",pat:"Core",eq:"Bodyweight",pri:["abs","hip_flexors"],sec:["obliques","forearms"],
 about:"Hanging from the bar and curling the pelvis up trains the lower abs and your grip at the same time.",
 form:["Dead hang, shoulders packed","Curl the pelvis up, not just the knees","No swinging between reps"]},
"Captain's Chair Raise":{g:"Core",pat:"Core",eq:"Machine",pri:["abs","hip_flexors"],sec:["obliques"],
 about:"Knee raises with the forearms on pads — the same lower-ab curl without grip being the limit.",
 form:["Press the lower back towards the pad","Curl the pelvis, don't just lift the knees","No swinging between reps"]},
"Hanging Leg Raise":{g:"Core",pat:"Core",eq:"Bodyweight",pri:["abs","hip_flexors"],sec:["obliques","forearms"],
 about:"The knee raise with straight legs — a much longer lever, and a real test of both abs and grip.",
 form:["Dead hang, shoulders packed","Raise straight legs to hip height or above by curling the pelvis","Lower slowly, no swinging"]},
"Reverse Crunch":{g:"Core",pat:"Core",eq:"Bodyweight",pri:["abs"],sec:["hip_flexors"],
 about:"Lying down and curling the hips off the floor towards the ribs — the lower-ab pattern of a hanging raise without needing a bar.",
 form:["Hands by the hips, knees bent","Curl the hips up and towards the chest","Lower slowly, don't let the feet touch down between reps"]},
"Weighted Sit-Up":{g:"Core",pat:"Core",eq:"Bodyweight",pri:["abs","hip_flexors"],sec:["obliques"],
 about:"A full sit-up holding a plate or dumbbell at the chest. Straightforward and easy to progress.",
 form:["Feet anchored, weight held at the chest","Sit all the way up, chest tall","Lower slowly through the whole range"]},
"Pallof Press":{uni:1,g:"Core",pat:"Core",eq:"Cable",pri:["obliques","abs"],sec:["delts_front"],
 about:"Standing side-on to a cable and pressing it straight out — the core's job is to refuse to rotate. Log reps per side.",
 form:["Cable at chest height, stand side-on with a wide stance","Press straight out and hold for a count","Bring it back without letting the torso twist"]},
"Cable Woodchop":{uni:1,g:"Core",pat:"Core",eq:"Cable",pri:["obliques","abs"],sec:["delts_front"],
 about:"A high-to-low diagonal pull across the body that trains rotation under load. Log reps per side.",
 form:["Cable set high, feet wide","Pull down and across to the opposite knee with the arms mostly straight","Rotate from the torso, not the arms"]},
"Plank":{timed:1,g:"Core",pat:"Core",eq:"Bodyweight",pri:["abs"],sec:["obliques","glutes"],
 about:"The forearm plank. Measured in seconds — use the stopwatch in the session. Log 0 kg unless you add a plate; do that once you are past 60 seconds.",
 form:["Elbows under the shoulders, body a straight line","Squeeze the glutes and brace the abs","Stop the set when the hips start to sag"]},
"Farmer's Carry":{timed:1,g:"Core",pat:"Core",eq:"Dumbbell",pri:["forearms","traps","abs"],sec:["obliques","glutes"],
 about:"A heavy dumbbell in each hand, walking tall. Grip, traps and the whole trunk work to keep you upright. Measured in seconds.",
 form:["Stand tall, shoulders back and down","Short quick steps, weights still","Put them down before the grip opens, not after"]},
"Suitcase Carry":{uni:1,timed:1,g:"Core",pat:"Core",eq:"Dumbbell",pri:["obliques","abs"],sec:["forearms","traps"],
 about:"Walking with a heavy dumbbell in one hand while staying perfectly upright — the obliques fight the lean the whole way. Timed per side; use the stopwatch.",
 form:["Stand tall, shoulders level","Walk slowly and deliberately","Don't let the weight pull you sideways"]}};

const DEFAULT_DAYS={
A:{title:"Squat & Horizontal Push",ex:[
 ["Back Squat","6–8",1],["Flat Dumbbell Bench Press","6–8",1],["Chest-Supported Row","8–10",1],
 ["Seated Leg Curl","10–12",0],["Seated DB Shoulder Press","10–12",0],["Cable Triceps Pushdown","12–15",0],
 ["Incline DB Curl","10–12",0],["Seated Calf Raise","12–15",0],["Cable Crunch","12–15",0]]},
B:{title:"Hinge & Vertical Pull",ex:[
 ["Romanian Deadlift","8–10",1],["Lat Pulldown","8–10",1],["Incline Dumbbell Press","8–10",1],
 ["Leg Press","10–12",0],["Cable Lateral Raise","12–15",0],["Overhead Cable Triceps Extension","12–15",0],
 ["Hammer Curl","10–12",0],["Hanging Knee Raise","10–15",0]]},
C:{title:"Unilateral & Pump",ex:[
 ["Hack Squat","10–12",1],["Seated Cable Row","8–10",1],["Machine Chest Press","10–12",1],
 ["45-Degree Back Extension","12–15",0],["DB Lateral Raise","15–20",0],["Reverse Pec Deck","15–20",0],
 ["Cable Curl","12–15",0],["Standing Calf Raise","10–15",0]]}};

/* Starting points for a new user. Any of these can be edited freely afterwards;
   "Build my own" is a single empty day that opens the programme editor. */
const PROGRAMME_TEMPLATES=[
  {id:"atlas",name:"ATLAS full body",tag:"3 days · full body",
   desc:"Squat, hinge and unilateral days with the big presses and pulls spread across the week. The original ATLAS programme.",
   programme:DEFAULT_DAYS},
  {id:"ul",name:"Upper / Lower",tag:"4 days · strength + hypertrophy",
   desc:"Two upper and two lower days. The first pair is heavier and lower-rep, the second pair chases volume.",
   programme:{
    A:{title:"Upper · Strength",ex:[["Barbell Bench Press","5–8",1],["Barbell Row","6–8",1],["Standing Barbell Overhead Press","6–8",1],["Lat Pulldown","8–10",0],["Incline DB Curl","10–12",0],["Cable Triceps Pushdown","12–15",0],["DB Lateral Raise","12–15",0]]},
    B:{title:"Lower · Strength",ex:[["Back Squat","5–8",1],["Romanian Deadlift","6–8",1],["Leg Press","10–12",0],["Seated Leg Curl","10–12",0],["Standing Calf Raise","10–15",0],["Cable Crunch","12–15",0]]},
    C:{title:"Upper · Hypertrophy",ex:[["Incline Dumbbell Press","8–12",1],["Chest-Supported Row","8–12",1],["Seated DB Shoulder Press","8–12",1],["Neutral-Grip Pulldown","10–12",0],["Cable Fly","12–15",0],["Face Pull","15–20",0],["Hammer Curl","10–12",0],["Overhead Cable Triceps Extension","12–15",0]]},
    D:{title:"Lower · Hypertrophy",ex:[["Hack Squat","8–12",1],["Barbell Hip Thrust","8–12",1],["Bulgarian Split Squat","10–12",0],["Lying Leg Curl","12–15",0],["Leg Extension","12–15",0],["Seated Calf Raise","12–15",0],["Hanging Knee Raise","10–15",0]]}}},
  {id:"ppl",name:"Push / Pull / Legs",tag:"6 days · each muscle twice a week",
   desc:"The classic six-day split. Heavier first half of the week, more volume in the second. Needs the time to train most days.",
   programme:{
    A:{title:"Push 1",ex:[["Barbell Bench Press","5–8",1],["Seated DB Shoulder Press","8–10",1],["Incline Dumbbell Press","8–12",0],["Cable Lateral Raise","12–15",0],["Cable Triceps Pushdown","12–15",0],["Overhead Cable Triceps Extension","12–15",0]]},
    B:{title:"Pull 1",ex:[["Conventional Deadlift","4–6",1],["Lat Pulldown","8–10",1],["Chest-Supported Row","8–10",1],["Face Pull","15–20",0],["Incline DB Curl","10–12",0],["Hammer Curl","10–12",0]]},
    C:{title:"Legs 1",ex:[["Back Squat","5–8",1],["Romanian Deadlift","8–10",1],["Leg Press","10–12",0],["Seated Leg Curl","10–12",0],["Standing Calf Raise","10–15",0],["Cable Crunch","12–15",0]]},
    D:{title:"Push 2",ex:[["Incline Barbell Press","6–8",1],["Machine Chest Press","10–12",1],["Arnold Press","10–12",0],["DB Lateral Raise","15–20",0],["Cable Fly","12–15",0],["Skull Crusher","10–12",0]]},
    E:{title:"Pull 2",ex:[["Barbell Row","6–8",1],["Pull-Up","6–10",1],["Seated Cable Row","10–12",1],["Reverse Pec Deck","15–20",0],["Cable Curl","12–15",0],["Barbell Shrug","10–12",0]]},
    F:{title:"Legs 2",ex:[["Hack Squat","8–12",1],["Barbell Hip Thrust","8–12",1],["Bulgarian Split Squat","10–12",0],["Lying Leg Curl","12–15",0],["Leg Extension","12–15",0],["Seated Calf Raise","12–15",0],["Hanging Leg Raise","10–15",0]]}}},
  {id:"physique",name:"ATLAS Physique",tag:"6 days · Mon to Sat · open-ended",
   desc:"Push / pull / legs twice through, biased to chest, shoulders, back width and arms. Every set 0 to 1 RIR, two ramp-in weeks, a light week every sixth week, and it never ends: weeks count up and every lift progresses on its own.",
   plan:PHYSIQUE_PLAN,
   programme:{
    A:{title:"Push A · chest",ex:[["Incline Barbell Press","6–10",1],["Flat Dumbbell Bench Press","8–12",1],["Low-to-High Cable Fly","12–15",0],["Seated DB Shoulder Press","8–12",1],["Cable Lateral Raise","12–20",0,{sets:4}],["Overhead Cable Triceps Extension","10–15",0],["Cable Triceps Pushdown","12–15",0],["Cable Crunch","12–15",0]]},
    B:{title:"Pull A · width",ex:[["Pull-Up","6–10",1],["Chest-Supported Row","8–12",1],["Wide-Grip Lat Pulldown","8–12",1],["Cable Rear Delt Fly","15–20",0],["Straight-Arm Pulldown","12–15",0],["Incline DB Curl","8–12",0],["Bayesian Cable Curl","12–15",0],["Hanging Leg Raise","10–15",0]]},
    C:{title:"Legs A · quads",ex:[["Hack Squat","8–12",1],["Romanian Deadlift","8–10",1],["Leg Extension","12–15",0],["Seated Leg Curl","10–15",0],["Standing Calf Raise","10–15",0,{sets:4}],["Lean-Away Lateral Raise","12–20",0],["Plank","45–60",0]]},
    D:{title:"Push B · shoulders",ex:[["Standing Barbell Overhead Press","6–10",1],["Incline Dumbbell Press","8–12",1],["Machine Chest Press","10–15",1],["Pec Deck","12–15",0],["DB Lateral Raise","12–20",0,{sets:4}],["Skull Crusher","8–12",0],["Single-Arm Cable Pushdown","12–15",0,{sets:2}],["Cable Rear Delt Fly","15–20",0,{sets:2}],["Cable Woodchop","12–15",0]]},
    E:{title:"Pull B · thickness",ex:[["Pendlay Row","6–10",1],["Lat Pulldown","8–12",1],["Single-Arm Cable Row","10–12",1],["Reverse Pec Deck","15–20",0,{sets:4}],["Face Pull","15–20",0],["Barbell Curl","8–12",0],["Spider Curl","10–15",0],["Weighted Sit-Up","12–15",0]]},
    F:{title:"Legs B · posterior",ex:[["Leg Press","10–15",1],["Barbell Hip Thrust","8–12",1],["Lying Leg Curl","12–15",0],["Bulgarian Split Squat","10–12",0,{sets:2}],["Seated Calf Raise","12–15",0,{sets:4}],["Cable Lateral Raise","15–20",0],["Overhead DB Extension","10–15",0]]}}},
  {id:"blank",name:"Build my own",tag:"start empty",
   desc:"One empty day and the full lift library. Add days, lifts, rep ranges and supersets yourself.",
   programme:{A:{title:"Day A",ex:[]}}}
];
if(typeof module!=="undefined"&&module.exports)module.exports={PHASES,PLAN_PRESETS,DEFAULT_PLAN,PHYSIQUE_PLAN,PROGRAMME_TEMPLATES,BIG_INC,DEFAULT_SETTINGS,PLATE_OPTIONS,isBarbellLift,SUBS,MUSCLE_NAMES,MUSCLE_MAP,GROUPS,EXDB,DEFAULT_DAYS};
